### ISSUE TITLE
Error too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by 7eta** [jsk1107/udk_labeler#2]
Active learning 누르면 progress 100 epoch 0 complete까지 잘 진행후 error too many values to unpack이 나옵니다.
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch로 설치했고 pycocotools, tensorboardX 제외하고
모든 패키지는 conda install로 설치했습니다.

python 3.7, Windows10 입니다.
CUDA및 CUDNN은 conda 가상환경에서 파이토치설치때 cudatoolkit 설치돼서 따로 설치 안했습니다.

디버깅하며 찾아보니 inference.py 86번째줄 
nms_scores, transformed_anchors = model(image) 부분에서 Error too many values to unpack (expected 2) 발생합니다.

**Comment by jsk1107** [comment]
@7eta 현재 코드상에 약간 문제가 있는거로 확인이 됩니다. 빠른 시일내에 수정하도록 하겠습니다.
가이드라인도 영상으로 만들 예정이니 조금만 기다려주세요...!

**Comment by jsk1107** [comment]
관련사항 에러 수정하였습니다.
현재 프로그램이 실행된 상태에서 이미지파일이나 xml파일을 이동하거나, 제거하는 액션이 있는경우 에러가 발생하게 됩니다. 이와 관련해서 예외처리가 필요한 부분이 있는데 조만간 추가하도록 하겠습니다.

죄송하지만 해당 프로젝트는 제 지인과 둘이서 진행하고 있기때문에 프로젝트 참여는 어려울것같습니다.
혹시 요구사항이 있으시면 이슈 남겨주세요. 빠르게 추가 및 수정하도록 하겠습니다.

**Comment by 7eta** [comment]
네, 알겠습니다. 
이 이슈는 여기서 종료하고 업데이트 후 새로운 이슈 말씀드리겠습니다.
