### ISSUE TITLE
error No module named 'model'

### ISSUE THREAD

**Issue by 7eta** [jsk1107/udk_labeler#3]
새로운 문제점이 발견되어 말씀드립니다.

첫 번째는, error [Errno 2] No such file or directory: 'pretrained_weight/coco_resnet_50_map_0_335_state_dict.pt' 입니다.
root폴더에 `pretrained_weight`폴더를 생성 후, https://drive.google.com/open?id=1yLmjq3JtXi841yXWBxst0coAgR26MNBS 에서 `coco_resnet_50_map_0_335_state_dict.pt` 파일을 다운받아 해결했습니다.

두 번째 문제는 error No module named 'model' 입니다.
`train.py` 57번째 줄 `checkpoint = torch.load(self.config.resume)` 이후로 해당 오류가 발생하는것으로 보입니다.

확인 부탁드리며, 저도 해결방법을 찾아보고 발견되면 공유하도록 하겠습니다.

**Comment by 7eta** [comment]
새로운 아나콘다 가상환경에서 처음부터 다시 셋팅했더니 정상적으로 작동 됩니다.

**Comment by jsk1107** [comment]
작업순서는 올바르게 진행하고 있습니다. 
70장의 이미지로는 아마 학습모델 생성이 잘 안되서 그런거 같습니다. 또한 모든 이미지는 512*512로 resize되는데 기존 해상도가 1920*1080에서 80px정도의 객체는 탐지가 안될것같습니다.

`/engine/cfg/config.py` 에서 lr값을 조절해보시면서(`1e-5` 이하의 값) Test를 해보시거나, 이미지 갯수를 좀 늘려주세요. 경험상으로는 class당 최소 100장 이상 필요하다고 판단됩니다. class의 이미지 분포가 다양한 형태라면 더욱 많은 이미지가 필요합니다.

추가적으로 현재 retinanet을 사용하고 있는데, 상당히 옛날 모델로 성능이 좋지 못합니다. 조만간 EfficientDet으로 교체할 예정입니다.

**Comment by 7eta** [comment]
답변 감사합니다.

추후에는 이런 기능도 들어갔으면 좋겠습니다.
1. COCO 데이터셋의 json파일로 저장되는 기능
2. 사용자 데이터로 학습된 파일을 추후에 새로운 이미지로 이어서 더 강한 어노테이션 및 라벨링 기능
3. Active Learning이 아닌, Machine Suggestion버튼이 추가되고, 기학습된 파일을 로드하여 File List의 이미지들을 어노테이션 및 라벨링 작업을 1차적으로 진행합니다. 나중엔 사용자는 버튼 하나 누르고, 다음버튼 누르며 일이 잘 진행됐나 확인만 하면되는 것입니다.  (customization 기능)

**Comment by jsk1107** [comment]
1번은 추가예정에 없습니다. `/engine/utils/voc2coco.py`를 활용하시면 변환하실 수 있습니다.
2번에 대해서는 고민중입니다. 학습이 완료된 pretrained_model을 지속적으로 사용하는 경우 Overfit이 되지 않을까 생각합니다. 
 해당부분은 여러번 시뮬레이션을 통해서 검증해보도록 하겠습니다.
3번은 추가 예정에 있습니다. 빠른 시간내에 추가할 수 있도록 하겠습니다.

이 프로젝트가 도움이 되신다니 저도 좋네요. 별도의 프로젝트로 개발하셔도 괜찮습니다. 혹은 기능추가에 대해서 PR 보내주시면 지인과 검토해서 적극 반영할 수 있도록 해보겠습니다.

**Comment by 7eta** [comment]
감사합니다. 별도의 프로젝트 공부하며 개발하도록 하겠습니다.
좋은 프로그램 공유해주셔서 고맙습니다. 오늘도 좋은 하루 보내시길 바랍니다. 
해당 이슈는 닫도록 하겠습니다.
